openapi: 3.0.0
info:
  title: Portfolio API
  description: API documentation for my portfolio
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /api/profile:
    get:
      summary: Get profile details
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  role:
                    type: string
                  about:
                    type: string
    post:
      summary: Create a new profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                role:
                  type: string
                about:
                  type: string
      responses:
        "201":
          description: Profile created successfully
